# Generated by Django 3.2.16 on 2022-11-08 12:58

import apps.place.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50, verbose_name='name')),
                ('place_slug', models.SlugField(max_length=10, verbose_name='slug')),
                ('place_information', models.TextField(verbose_name='information')),
                ('place_image_name', models.FileField(blank=True, null=True, upload_to=apps.place.models.upload_service_main_imgae, verbose_name='place_image_name')),
                ('visiting_day', models.CharField(blank=True, max_length=50, null=True, verbose_name='visiting_day')),
                ('visiting_hour', models.CharField(blank=True, max_length=50, null=True, verbose_name='visiting_hour')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='register_date')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'table_place',
            },
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.CharField(max_length=50, verbose_name='visitor_type')),
            ],
            options={
                'verbose_name': 'visitor_type',
                'verbose_name_plural': 'visitor_types',
                'db_table': 'table_visitor_type',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='place')),
                ('visitor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.visitortype', verbose_name='visitor_type')),
            ],
            options={
                'verbose_name': 'Ticket_price',
                'verbose_name_plural': 'Ticket_prices',
                'db_table': 'table_Ticket_price',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('place', models.ManyToManyField(to='place.Place')),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rules',
                'db_table': 'table_rule',
            },
        ),
    ]
