# Generated by Django 3.2.16 on 2022-11-08 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='family')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='register_time')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
                'db_table': 'table_contactform',
            },
        ),
    ]
