# FROM python:alpine3.15
# WORKDIR /app
# COPY /apps ./
# COPY . .
# RUN pip install --upgrade pip && \
#     pip install -r requirments.txt

# EXPOSE 8001
# CMD [ "python3","manage.py runserver" ]


FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /app/


